/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package grupo8_tp6_gestionproductos.vistas;

import clases.Producto;
import java.awt.event.KeyEvent;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author salon
 */
public class ViewNombre extends javax.swing.JInternalFrame {
    private DefaultTableModel modeloTabla = new DefaultTableModel()
    { //EXTRA podemos abrir llaves para configurar el metodo.SOBREESCRIBIR.SE LLAMA CLASE INTERN ANONIMA
          @Override
          //por cada celda de la tabla se ejecuta este metodo
        public boolean isCellEditable(int fila, int columna) {
        //return super.isCellEditable(fila, columna); //SI cambiamos el Return por false las tablas no son editables Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
                return false;
        } 
    
    }; 
    /**
     * Creates new form ViewPrecio
     */
    public ViewNombre() {
        initComponents();
        cabeceraGestion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfIngresoNombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtDescripcion = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-search-32.png"))); // NOI18N
        jLabel1.setText("Listado por nombre");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ingrese descripcion y precione \"Enter\":");

        jtfIngresoNombre.setBackground(new java.awt.Color(102, 102, 102));
        jtfIngresoNombre.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jtfIngresoNombre.setForeground(new java.awt.Color(255, 255, 255));
        jtfIngresoNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfIngresoNombreKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfIngresoNombreKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfIngresoNombreKeyTyped(evt);
            }
        });

        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        jtDescripcion.setBackground(new java.awt.Color(102, 102, 102));
        jtDescripcion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtDescripcion);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtfIngresoNombre))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtfIngresoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfIngresoNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfIngresoNombreKeyPressed
        // TODO add your handling code here:
        //METODO PRESIONANDO ENTER
//         modeloTabla.getDataVector().removeAllElements();
//         modeloTabla.fireTableDataChanged();
//         if(evt.getKeyCode()== KeyEvent.VK_ENTER){
//            String descripcion=jtfIngresoNombre.getText();
//             cargarDatos(descripcion);  
//         }
    }//GEN-LAST:event_jtfIngresoNombreKeyPressed

    private void jtfIngresoNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfIngresoNombreKeyTyped
        // TODO add your handling code here:
//        modeloTabla.getDataVector().removeAllElements();
//        modeloTabla.fireTableDataChanged();
//         String descripcion=jtfIngresoNombre.getText();
//         for (int i = 0; i < descripcion.length(); i++) {
//             System.out.println(i);
//            char descripcionChar = descripcion.charAt(i);  
//            cargarDatos(descripcionChar);
//        }
        
    }//GEN-LAST:event_jtfIngresoNombreKeyTyped

    private void jtfIngresoNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfIngresoNombreKeyReleased
        // TODO add your handling code here:
         String descripcion=jtfIngresoNombre.getText();
         for (int i = 0; i < descripcion.length(); i++) {
            char descripcionChar = descripcion.charAt(i); 
            modeloTabla.getDataVector().removeAllElements();
            modeloTabla.fireTableDataChanged();
            cargarDatos(descripcionChar);
        }
    }//GEN-LAST:event_jtfIngresoNombreKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtDescripcion;
    private javax.swing.JTextField jtfIngresoNombre;
    // End of variables declaration//GEN-END:variables
      private void cabeceraGestion(){
         this.modeloTabla.addColumn("Codigo");
         this.modeloTabla.addColumn("Descricpion");
         this.modeloTabla.addColumn("Precio");
         this.modeloTabla.addColumn("Categoria");
         this.modeloTabla.addColumn("Stock");
         jtDescripcion.setModel(modeloTabla);
    }
     private void cargarDatos(char descripcionChar){   
         for (Map.Entry<Long, Producto> en : ViewMenuPrincipal.mapaProductos.entrySet()) {
             Long key = en.getKey();
             Producto value = en.getValue();
                for (int i = 0; i < value.getDescripcion().length(); i++) {
                    char caracterValue=value.getDescripcion().charAt(i);
                     if(caracterValue==descripcionChar){
                       modeloTabla.addRow(new Object[]{key,value.getDescripcion(),value.getPrecio(),value.getRubro(),value.getStock()});  
                   }
             }
         }
     }
}
