/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package grupo8_tp6_gestionproductos.vistas;

import clases.Producto;
import java.util.Map;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author salon
 */
public class ViewCategoria extends javax.swing.JInternalFrame {
    private DefaultTableModel modeloTabla = new DefaultTableModel()
    { //EXTRA podemos abrir llaves para configurar el metodo.SOBREESCRIBIR.SE LLAMA CLASE INTERN ANONIMA
          @Override
          //por cada celda de la tabla se ejecuta este metodo
        public boolean isCellEditable(int fila, int columna) {
        //return super.isCellEditable(fila, columna); //SI cambiamos el Return por false las tablas no son editables Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
                return false;
        } 
    
    }; 
    /**
     * Creates new form ViewCategoria
     */
    public ViewCategoria() {
        initComponents();
        cabeceraGestion();
        inicializadorCombo();
    }
      private void inicializadorCombo(){
        jcbCategoriaBuscar.addItem("Perfumeria");
        jcbCategoriaBuscar.addItem("Comestible");
        jcbCategoriaBuscar.addItem("Limpieza");
        jcbCategoriaBuscar.addItem("Farmacia");
        jcbCategoriaBuscar.addItem("Ropa");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpPress = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtCategoria = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jcbCategoriaBuscar = new javax.swing.JComboBox<>();

        jpPress.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-search-32.png"))); // NOI18N
        jLabel1.setText("Listado por categoria");

        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        jtCategoria.setBackground(new java.awt.Color(102, 102, 102));
        jtCategoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtCategoria);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Categoria:");

        jcbCategoriaBuscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jcbCategoriaBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbCategoriaBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpPressLayout = new javax.swing.GroupLayout(jpPress);
        jpPress.setLayout(jpPressLayout);
        jpPressLayout.setHorizontalGroup(
            jpPressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPressLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(jpPressLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jpPressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPressLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jcbCategoriaBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpPressLayout.setVerticalGroup(
            jpPressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPressLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jpPressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcbCategoriaBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpPress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpPress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbCategoriaBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbCategoriaBuscarActionPerformed
        // TODO add your handling code here:
         modeloTabla.getDataVector().removeAllElements();
         modeloTabla.fireTableDataChanged();
         String itemCategoria=(String) jcbCategoriaBuscar.getSelectedItem();
        cargarDatos(itemCategoria);
    }//GEN-LAST:event_jcbCategoriaBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcbCategoriaBuscar;
    private javax.swing.JPanel jpPress;
    private javax.swing.JTable jtCategoria;
    // End of variables declaration//GEN-END:variables
    private void cabeceraGestion(){
         this.modeloTabla.addColumn("Codigo");
         this.modeloTabla.addColumn("Descricpion");
         this.modeloTabla.addColumn("Precio");
         this.modeloTabla.addColumn("Categoria");
         this.modeloTabla.addColumn("Stock");
         jtCategoria.setModel(modeloTabla);
    }
     private void cargarDatos(String itemCategoria){
         for (Map.Entry<Long, Producto> en : ViewMenuPrincipal.mapaProductos.entrySet()) {
             Long key = en.getKey();
             Producto value = en.getValue();
             if(value.getRubro().equalsIgnoreCase(itemCategoria)){
              modeloTabla.addRow(new Object[]{key,value.getDescripcion(),value.getPrecio(),value.getRubro(),value.getStock()});  
             
           }  
         }
     }
}
