/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package grupo8_tp6_gestionproductos.vistas;

import clases.Producto;
import java.awt.event.KeyEvent;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author salon
 */
public class ViewPrecio extends javax.swing.JInternalFrame {
    private DefaultTableModel modeloTabla = new DefaultTableModel()
    { //EXTRA podemos abrir llaves para configurar el metodo.SOBREESCRIBIR.SE LLAMA CLASE INTERN ANONIMA
          @Override
          //por cada celda de la tabla se ejecuta este metodo
        public boolean isCellEditable(int fila, int columna) {
        //return super.isCellEditable(fila, columna); //SI cambiamos el Return por false las tablas no son editables Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
                return false;
        } 
    
    }; 
    /**
     * Creates new form ViewPrecio
     */
    public ViewPrecio() {
        initComponents();
        cabeceraGestion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpPress = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtPrecio = new javax.swing.JTable();
        jtfNumeroMenor = new javax.swing.JTextField();
        jtfNumeroMayor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        jpPress.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-search-32.png"))); // NOI18N
        jLabel1.setText("Listado por precio");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ingrese precio entre los valores:");

        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        jtPrecio.setBackground(new java.awt.Color(102, 102, 102));
        jtPrecio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtPrecio);

        jtfNumeroMenor.setBackground(new java.awt.Color(102, 102, 102));
        jtfNumeroMenor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jtfNumeroMenor.setForeground(new java.awt.Color(255, 255, 255));
        jtfNumeroMenor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfNumeroMenorKeyReleased(evt);
            }
        });

        jtfNumeroMayor.setBackground(new java.awt.Color(102, 102, 102));
        jtfNumeroMayor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jtfNumeroMayor.setForeground(new java.awt.Color(255, 255, 255));
        jtfNumeroMayor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfNumeroMayorKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfNumeroMayorKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Y");

        javax.swing.GroupLayout jpPressLayout = new javax.swing.GroupLayout(jpPress);
        jpPress.setLayout(jpPressLayout);
        jpPressLayout.setHorizontalGroup(
            jpPressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPressLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jpPressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jpPressLayout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(jtfNumeroMenor, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jtfNumeroMayor))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpPressLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jpPressLayout.setVerticalGroup(
            jpPressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPressLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(jpPressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfNumeroMenor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfNumeroMayor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpPress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpPress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfNumeroMayorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNumeroMayorKeyPressed
        // TODO add your handling code here:
        
        //METODO PRESIONANDO ENTER
        
//        modeloTabla.getDataVector().removeAllElements();
//        modeloTabla.fireTableDataChanged();
//        
//        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
//           int numOne = Integer.parseInt(jtfNumeroMenor.getText());
//           int numTwo = Integer.parseInt(jtfNumeroMayor.getText());
//           cargarDatos(numOne,numTwo);
//        }

    }//GEN-LAST:event_jtfNumeroMayorKeyPressed

    private void jtfNumeroMenorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNumeroMenorKeyReleased
        // TODO add your handling code here:
        try{
           modeloTabla.getDataVector().removeAllElements();
           modeloTabla.fireTableDataChanged();
           int numOne = Integer.parseInt(jtfNumeroMenor.getText());
           int numTwo = Integer.parseInt(jtfNumeroMayor.getText());
            cargarDatos(numOne,numTwo);
        }catch(NumberFormatException e){
            
        }
    }//GEN-LAST:event_jtfNumeroMenorKeyReleased

    private void jtfNumeroMayorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNumeroMayorKeyReleased
        // TODO add your handling code here:
        try{
           modeloTabla.getDataVector().removeAllElements();
           modeloTabla.fireTableDataChanged();
           int numOne = Integer.parseInt(jtfNumeroMenor.getText());
           int numTwo = Integer.parseInt(jtfNumeroMayor.getText());
           cargarDatos(numOne,numTwo);
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "No hay productos almacenados", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jtfNumeroMayorKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpPress;
    private javax.swing.JTable jtPrecio;
    private javax.swing.JTextField jtfNumeroMayor;
    private javax.swing.JTextField jtfNumeroMenor;
    // End of variables declaration//GEN-END:variables
    private void cabeceraGestion(){
         this.modeloTabla.addColumn("Codigo");
         this.modeloTabla.addColumn("Descricpion");
         this.modeloTabla.addColumn("Precio");
         this.modeloTabla.addColumn("Categoria");
         this.modeloTabla.addColumn("Stock");
         jtPrecio.setModel(modeloTabla);
    }
     private void cargarDatos(int numOne, int numTwo){   
         for (Map.Entry<Long, Producto> en : ViewMenuPrincipal.mapaProductos.entrySet()) {
             Long key = en.getKey();
             Producto value = en.getValue();
             int precio = value.getPrecio();
             if(numOne<=precio && precio<=numTwo){
                modeloTabla.addRow(new Object[]{key,value.getDescripcion(),value.getPrecio(),value.getRubro(),value.getStock()});  
             
             }  
         }
     }
}
